# ALMOR configuration

# Location of the ALMOR database(s).
ALMOR.text.database.path=resources
#ALMOR.text.MSA.database.name=almor-s31.db
#ALMOR.text.EGY.database.name=almor-c044.db
ALMOR.text.MSA.database.name=almor-msa-r13.db
ALMOR.text.EGY.database.name=almor-cra07.db